language: objective-c
osx_image: xcode10.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

addons:
  homebrew:
    packages:
    - curl # Fix the codecov upload issue

cache: cocoapods
podfile: Podfile

before_install:
    - env
    - locale
    - gem install cocoapods --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings --skip-tests # Will run test below

    - echo Clean DerivedData
    - rm -rf ~/Library/Developer/Xcode/DerivedData/

    - echo Build as dynamic frameworks
    - xcodebuild build -project YPhotoPicker.xcodeproj -scheme 'YPhotoPicker' -sdk iphonesimulator -configuration Debug | xcpretty -c

    - mv ~/Library/Developer/Xcode/DerivedData/ ./DerivedData/iOS

after_success:
    - export PATH="/usr/local/opt/curl/bin:$PATH"
    - curl --version
    - bash <(curl -s https://codecov.io/bash) -D './DerivedData/iOS' -J '^YPhotoPicker$' -c -X gcov -F ios